In [1]:
import numpy as np

# Pandas, conventionally imported as pd
import pandas as pd

Pandas is primary tool for handling data.
Primary object DataFrame

Explore functionality here and use it in the next lesson

In [2]:
!head data/gfmt_sleep.csv

ï»¿participant number,gender,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence when incorrect hit,confidence when correct reject,confidence when incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess
8,f,39,65,80,72.5,91,90,93,83.5,93,90,9,13,2
16,m,42,90,90,90,75.5,55.5,70.5,50,75,50,4,11,7
18,f,31,90,95,92.5,89.5,90,86,81,89,88,10,9,3
22,f,35,100,75,87.5,89.5,*,71,80,88,80,13,8,20
27,f,74,60,65,62.5,68.5,49,61,49,65,49,13,9,12
28,f,61,80,20,50,71,63,31,72.5,64.5,70.5,15,14,2
30,m,32,90,75,82.5,67,56.5,66,65,66,64,16,9,3
33,m,62,45,90,67.5,54,37,65,81.5,62,61,14,9,9
34,f,33,80,100,90,70.5,76.5,64.5,*,68,76.5,14,12,10

* denotes missing data

Pandas has pd.read_csv() that reads CSV and stores the contents in a data frame

Data type for a data frame is DataFrame

In [39]:
#pd.read_csv?

We only need the na_values kwarg
    Specifies what characters signify that a data point is missing
    Resulting data frame is populated wieth a NaN wherever this character is present in the file

In [4]:
df = pd.read_csv('data/gfmt_sleep.csv', na_values='*')

#check the type
type(df)

pandas.core.frame.DataFrame

In [5]:
df

,participant number,gender,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence when incorrect hit,confidence when correct reject,confidence when incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess
0,8,f,39,65,80,72.5,91.0,90.0,93.0,83.5,93.0,90.0,9,13,2
1,16,m,42,90,90,90.0,75.5,55.5,70.5,50.0,75.0,50.0,4,11,7
2,18,f,31,90,95,92.5,89.5,90.0,86.0,81.0,89.0,88.0,10,9,3
3,22,f,35,100,75,87.5,89.5,NaN,71.0,80.0,88.0,80.0,13,8,20
4,27,f,74,60,65,62.5,68.5,49.0,61.0,49.0,65.0,49.0,13,9,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,97,f,23,70,85,77.5,77.0,66.5,77.0,77.5,77.0,74.0,20,8,10
98,98,f,70,90,85,87.5,65.5,85.5,87.0,80.0,74.0,80.0,19,8,7
99,99,f,24,70,80,75.0,61.5,81.0,70.0,61.0,65.0,81.0,31,2,15
100,102,f,40,75,65,70.0,53.0,37.0,84.0,52.0,81.0,51.0,22,4,7
101,103,f,33,85,40,62.5,80.0,27.0,31.0,82.5,81.0,73.0,24,5,7

In [6]:
df.head()

,participant number,gender,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence when incorrect hit,confidence when correct reject,confidence when incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess
0,8,f,39,65,80,72.5,91.0,90.0,93.0,83.5,93.0,90.0,9,13,2
1,16,m,42,90,90,90.0,75.5,55.5,70.5,50.0,75.0,50.0,4,11,7
2,18,f,31,90,95,92.5,89.5,90.0,86.0,81.0,89.0,88.0,10,9,3
3,22,f,35,100,75,87.5,89.5,NaN,71.0,80.0,88.0,80.0,13,8,20
4,27,f,74,60,65,62.5,68.5,49.0,61.0,49.0,65.0,49.0,13,9,12

* We index DataFrames by columns
*

In [7]:
df['percent correct']

0      72.5
1      90.0
2      92.5
3      87.5
4      62.5
       ...
97     77.5
98     87.5
99     75.0
100    70.0
101    62.5
Name: percent correct, Length: 102, dtype: float64

In [8]:
# can pull out specific row, too
df['percent correct'][4]

62.5

In [9]:
# better to use .loc then the way above
df.loc[4, 'percent correct']

62.5

## Boolean indexing of data frames

In [10]:
df.loc[df['participant number'] == 42, 'percent correct']

54    85.0
Name: percent correct, dtype: float64

In [11]:
# can pull whole record for that participant

df.loc[df['participant number'] == 42, :]

,participant number,gender,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence when incorrect hit,confidence when correct reject,confidence when incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess
54,42,m,29,100,70,85.0,75.0,NaN,64.5,43.0,74.0,43.0,32,1,6

In [13]:
# pull out all records of females under the age of 21

df.loc[(df['age'] < 21) & (df['gender'] == 'f'), :]

,participant number,gender,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence when incorrect hit,confidence when correct reject,confidence when incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess
27,3,f,16,70,80,75.0,70.0,57.0,54.0,53.0,57.0,54.5,23,1,3
29,5,f,18,90,100,95.0,76.5,83.0,80.0,NaN,80.0,83.0,21,7,5
66,58,f,16,85,85,85.0,55.0,30.0,50.0,40.0,52.5,35.0,29,2,11
79,72,f,18,80,75,77.5,67.5,51.5,66.0,57.0,67.0,53.0,29,4,6
88,85,f,18,85,85,85.0,93.0,92.0,91.0,89.0,91.5,91.0,25,4,21

In [14]:
# pull out all females under 30 who got ore than 85% of the face matching 
# tests correc

# clearer to se t up Boolean indexing first

inds = (df['age'] < 30) & (df['gender'] == 'f') & (df['percent correct'] > 85)

# take a look
inds

0      False
1      False
2      False
3      False
4      False
       ...
97     False
98     False
99     False
100    False
101    False
Length: 102, dtype: bool

In [15]:
df.loc[inds,:]

,participant number,gender,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence when incorrect hit,confidence when correct reject,confidence when incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess
22,93,f,28,100,75,87.5,89.5,NaN,67.0,60.0,80.0,60.0,16,7,4
29,5,f,18,90,100,95.0,76.5,83.0,80.0,NaN,80.0,83.0,21,7,5
30,6,f,28,95,80,87.5,100.0,85.0,94.0,61.0,99.0,65.0,19,7,12
33,10,f,25,100,100,100.0,90.0,NaN,85.0,NaN,90.0,NaN,17,10,11
56,44,f,21,85,90,87.5,66.0,29.0,70.0,29.0,67.0,29.0,26,7,18
58,48,f,23,90,85,87.5,67.0,47.0,69.0,40.0,67.0,40.0,18,6,8
60,51,f,24,85,95,90.0,97.0,41.0,74.0,73.0,83.0,55.5,29,1,7
75,67,f,25,100,100,100.0,61.5,NaN,58.5,NaN,60.5,NaN,28,8,9

In [17]:
# of interest in Boolean indexing is that we never had to write a looop

# we could have done the following

# Initialize array of Boolean indices
inds = [False] * len(df)

# Iterate over the rows to check if the row should be included
for i, r in df.iterrows():
    if r['age'] < 30 and r['gender'] == 'f' and r['percent correct'] > 85:
        inds[i] = True
        
# make out selection with Boolean indexing
df.loc[inds, :]

,participant number,gender,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence when incorrect hit,confidence when correct reject,confidence when incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess
22,93,f,28,100,75,87.5,89.5,NaN,67.0,60.0,80.0,60.0,16,7,4
29,5,f,18,90,100,95.0,76.5,83.0,80.0,NaN,80.0,83.0,21,7,5
30,6,f,28,95,80,87.5,100.0,85.0,94.0,61.0,99.0,65.0,19,7,12
33,10,f,25,100,100,100.0,90.0,NaN,85.0,NaN,90.0,NaN,17,10,11
56,44,f,21,85,90,87.5,66.0,29.0,70.0,29.0,67.0,29.0,26,7,18
58,48,f,23,90,85,87.5,67.0,47.0,69.0,40.0,67.0,40.0,18,6,8
60,51,f,24,85,95,90.0,97.0,41.0,74.0,73.0,83.0,55.5,29,1,7
75,67,f,25,100,100,100.0,61.5,NaN,58.5,NaN,60.5,NaN,28,8,9

## Calculating with data frames

Subject hsa insomnia if SCI is 16 or lower

Might want to add column to specify if subject has insomnia

In [18]:
df['sci'] <= 16

0       True
1       True
2       True
3       True
4       True
       ...
97     False
98     False
99     False
100    False
101    False
Name: sci, Length: 102, dtype: bool

In [19]:
# add the column to the data frame
df['insomnia'] = df['sci'] <= 16

# Take a look
df.head()

,participant number,gender,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence when incorrect hit,confidence when correct reject,confidence when incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess,insomnia
0,8,f,39,65,80,72.5,91.0,90.0,93.0,83.5,93.0,90.0,9,13,2,True
1,16,m,42,90,90,90.0,75.5,55.5,70.5,50.0,75.0,50.0,4,11,7,True
2,18,f,31,90,95,92.5,89.5,90.0,86.0,81.0,89.0,88.0,10,9,3,True
3,22,f,35,100,75,87.5,89.5,NaN,71.0,80.0,88.0,80.0,13,8,20,True
4,27,f,74,60,65,62.5,68.5,49.0,61.0,49.0,65.0,49.0,13,9,12,True

## Note about vectorization

## Applying functions to Pandas objects

In [21]:
print('Insomniacs:', np.mean(df.loc[df['insomnia'], 'percent correct']))
print('Control:   ', np.mean(df.loc[~df['insomnia'], 'percent correct']))

Insomniacs: 76.1
Control:    81.46103896103897

~ operator:
* Bit switcher
* Changes all Trues to Flases and vice versa
* It functions like a logical not

In [23]:
# can quickly compute summary statistics for each column
df.describe()

,participant number,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence when incorrect hit,confidence when correct reject,confidence when incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess
count,102.000000,102.000000,102.000000,102.000000,102.000000,102.000000,84.000000,102.000000,93.000000,102.000000,99.000000,102.000000,102.000000,102.000000
mean,52.049020,37.921569,83.088235,77.205882,80.147059,74.990196,58.565476,71.137255,61.220430,74.642157,61.979798,22.245098,5.274510,7.294118
std,30.020909,14.029450,15.091210,17.569854,12.047881,14.165916,19.560653,14.987479,17.671283,13.619725,15.921670,7.547128,3.404007,4.426715
min,1.000000,16.000000,35.000000,20.000000,40.000000,29.500000,7.000000,19.000000,17.000000,24.000000,24.500000,0.000000,0.000000,0.000000
25%,26.250000,26.500000,75.000000,70.000000,72.500000,66.000000,46.375000,64.625000,50.000000,66.000000,51.000000,17.000000,3.000000,4.000000
50%,52.500000,36.500000,90.000000,80.000000,83.750000,75.000000,56.250000,71.250000,61.000000,75.750000,61.500000,23.500000,5.000000,7.000000
75%,77.750000,45.000000,95.000000,90.000000,87.500000,86.500000,73.500000,80.000000,74.000000,82.375000,73.000000,29.000000,7.000000,10.000000
max,103.000000,74.000000,100.000000,100.000000,100.000000,100.000000,92.000000,100.000000,100.000000,100.000000,100.000000,32.000000,15.000000,21.000000

In [24]:
df.describe().loc['50%', :]

participant number                  52.50
age                                 36.50
correct hit percentage              90.00
correct reject percentage           80.00
percent correct                     83.75
confidence when correct hit         75.00
confidence when incorrect hit       56.25
confidence when correct reject      71.25
confidence when incorrect reject    61.00
confidence when correct             75.75
confidence when incorrect           61.50
sci                                 23.50
psqi                                 5.00
ess                                  7.00
Name: 50%, dtype: float64

## Outputing a new CSV file

In [30]:
# use df.to_csv() for this iwth the index kwarg to ask Pandas not to explicitly
# write the indices to the file

df.to_csv('gfmt_sleep_with_insomnia.csv', index=False)

In [31]:
!head gfmt_sleep_with_insomnia.csv

participant number,gender,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence when incorrect hit,confidence when correct reject,confidence when incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess,insomnia
8,f,39,65,80,72.5,91.0,90.0,93.0,83.5,93.0,90.0,9,13,2,True
16,m,42,90,90,90.0,75.5,55.5,70.5,50.0,75.0,50.0,4,11,7,True
18,f,31,90,95,92.5,89.5,90.0,86.0,81.0,89.0,88.0,10,9,3,True
22,f,35,100,75,87.5,89.5,,71.0,80.0,88.0,80.0,13,8,20,True
27,f,74,60,65,62.5,68.5,49.0,61.0,49.0,65.0,49.0,13,9,12,True
28,f,61,80,20,50.0,71.0,63.0,31.0,72.5,64.5,70.5,15,14,2,True
30,m,32,90,75,82.5,67.0,56.5,66.0,65.0,66.0,64.0,16,9,3,True
33,m,62,45,90,67.5,54.0,37.0,65.0,81.5,62.0,61.0,14,9,9,True
34,f,33,80,100,90.0,70.5,76.5,64.5,,68.0,76.5,14,12,10,True

## Styling a data frame

In [35]:
# highlight rows corresponding to women who scored at or above 75%
def highlight_high_scoring_females(s):
    if s['gender'] == 'f' and s['percent correct'] >= 75:
        return ['background-color: #7fc97f'] * len(s)
    else:
        return ['background-color: lightgray'] * len(s)
    
df.head(10).style.apply(highlight_high_scoring_females, axis=1)

In [36]:
# Want percent correct column with a bar corresponding to value in the column

# df.syle.bar() 
# subset kwarg specifies which columns are to have bars

df.head(10).style.bar(subset=['percent correct'], vmin=0, vmax=100)

In [38]:
df.head(10).style.background_gradient(subset=['percent correct'], cmap='Reds')